Repository re-Duck/reDuck-client, pull requests merged in 2023-05, with the labels that each got.

#15 게시글 작성 페이지
  client/package.json
  client/src/components/Navigator/index.tsx
  client/src/components/QuillEditBox/index.tsx
  client/src/components/index.tsx
  client/src/constant.ts
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/write/index.tsx
  client/src/service/BoardPost.ts
  client/src/service/base/api.ts
  client/src/service/loginPost.ts
  client/src/styles/globals.css
  client/src/util/index.ts
Labels: UI, Feature

#19 hotfix : import 파일 명 오타 수정
  client/src/pages/write/index.tsx
Labels: Bug

#21 메인페이지 게시글 fetch 및 게시글 작성 버튼 구현
  client/.eslintrc.json
  client/package.json
  client/src/components/Layout/index.tsx
  client/src/components/LoadingIcon/index.tsx
  client/src/components/Post/post-detail.tsx
  client/src/components/Post/post.tsx
  client/src/components/QuillEditBox/index.tsx
  client/src/components/WritePostButton/index.tsx
  client/src/components/index.tsx
  client/src/constant.ts
  client/src/pages/_app.tsx
  client/src/pages/board/[id].tsx
  client/src/pages/index.tsx
  client/src/pages/write/index.tsx
  client/src/service/BoardPost.ts
  client/src/service/base/api.ts
  client/src/service/getPosts.ts
  client/src/types/index.ts
  client/src/util/index.ts
Labels: UI, Feature

#23 이미지 불러오기 기능 구현
  client/src/components/Post/comment.tsx
  client/src/components/Post/post-detail.tsx
  client/src/components/QuillEditBox/index.tsx
  client/src/pages/board/[id].tsx
  client/src/pages/index.tsx
  client/src/pages/write/index.tsx
  client/src/service/BoardPost.ts
  client/src/service/base/api.ts
  client/src/service/getPosts.ts
  client/src/service/uploadImagePost.ts
  client/src/types/index.ts
Labels: UI, Feature

#20 회원가입, 로그인 API 연동 및 로그인 유지
  client/package.json
  client/src/components/AuthComponent/index.tsx
  client/src/components/index.tsx
  client/src/constant.ts
  client/src/lib/redux/reducer/index.ts
  client/src/lib/redux/slices/authSlice.ts
  client/src/lib/redux/store/index.ts
  client/src/pages/_app.tsx
  client/src/pages/api/auth/[...nextauth].ts
  client/src/pages/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/signup/index.tsx
  client/src/service/base/api.ts
  client/src/service/loginPost.ts
  client/src/service/signup.ts
  client/src/types/next-auth.d.ts
Labels: Feature

#26 유저 정보로 게시글 작성하기
  client/next.config.js
  client/src/components/AuthComponent/index.tsx
  client/src/components/QuillEditBox/index.tsx
  client/src/components/WritePostButton/index.tsx
  client/src/lib/redux/slices/authSlice.ts
  client/src/pages/api/auth/[...nextauth].ts
  client/src/pages/board/[id].tsx
  client/src/pages/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/write/index.tsx
  client/src/service/BoardPost.ts
  client/src/service/base/api.ts
  client/src/service/getPosts.ts
  client/src/types/next-auth.d.ts
Labels: UX, Feature

#30 마이페이지 mock-up 및 로그아웃 구현
  client/src/components/Avatar/index.tsx
  client/src/components/MenuView/index.tsx
  client/src/components/Navigator/index.tsx
  client/src/constant.ts
  client/src/pages/profile/[id].tsx
  client/src/styles/styleConstant.ts
Labels: UI, Feature

#36 이미지 경로 설정 및 크기 수정
  client/src/components/Post/comment-upload.tsx
  client/src/components/Post/comment.tsx
  client/src/components/Post/post-detail.tsx
Labels: Bug

#39 Redux 를 이용한 modal 구현
  client/src/components/Modal/index.tsx
  client/src/components/Modal/modal-button.tsx
  client/src/components/Modal/modal-icon.tsx
  client/src/components/Post/comment-upload.tsx
  client/src/components/Post/post-detail.tsx
  client/src/components/WritePostButton/index.tsx
  client/src/constant.ts
  client/src/hooks/index.ts
  client/src/hooks/useModal.ts
  client/src/lib/redux/reducer/index.ts
  client/src/lib/redux/slices/modalSlice.ts
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/write/index.tsx
Labels: DX, Feature

#41 게시글 삭제 및 댓글 삭제 기능
  client/public/favicon.ico
  client/public/main-duck.png
  client/src/assets/images/user_icon.png
  client/src/components/Divider/index.tsx
  client/src/components/Icon/index.tsx
  client/src/components/LoadingIcon/index.tsx
  client/src/components/MenuView/index.tsx
  client/src/components/Modal/index.tsx
  client/src/components/Navigator/index.tsx
  client/src/components/Post/comment-upload.tsx
  client/src/components/Post/comment.tsx
  client/src/components/Post/delete-button.tsx
  client/src/components/Post/index.tsx
  client/src/components/Post/modify-comment-button.tsx
  client/src/components/Post/modify-content-button.tsx
  client/src/components/Post/post-detail.tsx
  client/src/components/QuillEditBox/index.tsx
  client/src/components/WritePostButton/index.tsx
  client/src/constant.ts
  client/src/hooks/useModal.ts
  client/src/lib/redux/slices/modalSlice.ts
  client/src/lib/redux/store/index.ts
  client/src/pages/_document.tsx
  client/src/pages/board/[id].tsx
  client/src/pages/index.tsx
  client/src/pages/signup/index.tsx
  client/src/pages/write/index.tsx
  client/src/service/base/api.ts
  client/src/service/board-update.ts
  client/src/service/delete-comment.ts
  client/src/service/delete-post.ts
  client/src/service/update-comment.ts
  client/src/styles/globals.css
  client/src/types/index.ts
  client/src/util/index.ts
Labels: DX, UX, Feature

#45 마이페이지 - 개인정보 수정
  client/src/components/EditProfile/index.tsx
  client/src/components/UserInfo/flex-label-content.tsx
  client/src/components/UserInfo/index.tsx
  client/src/components/index.tsx
  client/src/constant.ts
  client/src/pages/profile/[id].tsx
  client/src/service/base/api.ts
  client/src/service/edit-profile.ts
  client/src/types/index.ts
Labels: UI, Feature

#50 fix : postOriginId 파라미터 데이터 수정
  client/src/components/Post/post-detail.tsx
Labels: Bug
