Repository re-Duck/reDuck-client, pull requests merged in 2023-06, with the labels that each got.

#55 데이터 게시글 및 모달 UX 개선
  client/src/components/Layout/index.tsx
  client/src/components/MenuView/index.tsx
  client/src/components/Modal/index.tsx
  client/src/components/Modal/modal-button.tsx
  client/src/components/Navigator/index.tsx
  client/src/components/Post/comment-upload.tsx
  client/src/components/Post/delete-button.tsx
  client/src/components/Post/post-detail.tsx
  client/src/constant.ts
  client/src/pages/board/[id].tsx
  client/src/pages/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/signup/index.tsx
  client/src/pages/write/index.tsx
  client/src/service/board-post.ts
  client/src/service/delete-comment.ts
  client/src/styles/globals.css
Labels: UX, Bug

#58 게시글 폰트 CSS 수정
  client/src/components/Post/post-detail.tsx
  client/src/styles/globals.css
Labels: UI

#56 회원가입 로직 변경
  client/src/components/Avatar/index.tsx
  client/src/components/EditProfile/index.tsx
  client/src/components/Modal/index.tsx
  client/src/components/Post/post-detail.tsx
  client/src/components/UserInfo/index.tsx
  client/src/components/WritePostButton/index.tsx
  client/src/constant.ts
  client/src/pages/profile/[id].tsx
  client/src/pages/signup/index.tsx
  client/src/service/sign-up.ts
  client/src/styles/styleConstant.ts
  client/src/types/index.ts
Labels: UX

#60 모바일 반응형 ui 버그 수정
  client/src/components/Navigator/index.tsx
  client/src/components/Post/comment-upload.tsx
  client/src/components/Post/post-detail.tsx
Labels: UI, Bug

#65 회원탈퇴 기능 추가
  client/src/constant.ts
  client/src/pages/profile/[id].tsx
  client/src/service/withdrawal.ts
  client/src/styles/globals.css
Labels: Feature

#66 메인 게시글 작성자 표시 UI
  client/src/components/Post/comment-upload.tsx
  client/src/components/Post/comment.tsx
  client/src/components/Post/post-detail.tsx
  client/src/components/Post/post.tsx
Labels: UI, UX

#68 댓글 비로그인 유저 이미지 추가
  client/src/components/Post/comment-upload.tsx
Labels: Bug

#72 프로필 업데이트 버그 수정
  client/.gitignore
  client/package-lock.json
  client/src/components/EditProfile/index.tsx
  client/src/components/Navigator/index.tsx
  client/src/components/Post/comment-upload.tsx
  client/src/constant.ts
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/api/auth/[...nextauth].ts
  client/src/pages/profile/[id].tsx
  client/src/service/edit-profile.ts
  client/src/types/index.ts
Labels: UX, Feature, Bug

#73 메인 페이지 위치 유지 구현
  client/src/components/Post/comment-upload.tsx
  client/src/components/Post/post.tsx
  client/src/pages/board/[id].tsx
  client/src/pages/index.tsx
  client/src/types/index.ts
Labels: UX

#75 회원가입시 비밀번호 양식알려주기/아이디 한글입력 방지
  client/src/constant.ts
  client/src/pages/login/index.tsx
  client/src/pages/signup/index.tsx
Labels: UX, Bug

#81 dx: ci/cd yml 파일 추가
  client/.github/test-lint-build.yml
Labels: DX

#86 개발환경과 배포 환경 baseurl 수정
  client/next.config.js
  client/src/pages/_app.tsx
  client/src/service/base/api.ts
Labels: DX
