Repository re-Duck/reDuck-client, pull requests merged in 2023-12, with the labels that each got.

#120 폼 컴포넌트화 및 마이페이지 반응형 제작
  client/public/images/advertise.png
  client/public/images/google_logo.png
  client/public/images/user_icon.png
  client/src/components/common/Advertisement/index.tsx
  client/src/components/common/Avatar/index.tsx
  client/src/components/common/EditProfile/index.tsx
  client/src/components/common/Form/Box/index.tsx
  client/src/components/common/Form/Button/index.tsx
  client/src/components/common/Form/Container/index.tsx
  client/src/components/common/Form/Description/index.tsx
  client/src/components/common/Form/Error/index.tsx
  client/src/components/common/Form/Input/index.tsx
  client/src/components/common/Form/Label/index.tsx
  client/src/components/common/Form/index.tsx
  client/src/components/common/UserInfo/index.tsx
  client/src/components/index.tsx
  client/src/constants/constant.ts
  client/src/hooks/Form/useEmail.ts
  client/src/hooks/Form/useInputImage.ts
  client/src/pages/login/index.tsx
  client/src/pages/profile/[id].tsx
  client/src/pages/signup/index.tsx
  client/src/service/email/checkProfileEmailNumber.ts
  client/src/service/email/sendProfileEmail.ts
  client/src/service/user/updateUser.ts
  client/src/types/index.ts
Labels: DX, UX, Refactor

#121 게시글 작성 중 이미지 크기 수정
  client/package.json
  client/src/components/board/PostDetail/index.tsx
  client/src/hooks/Write/useTiptap.ts
  client/yarn.lock
Labels: UX, Feature

#126 window에서 이미지 스크롤 생기는 버그
  .github/workflows/lighthouse.yml
  client/src/styles/globals.css
Labels: Bug
