Repository re-Duck/reDuck-client, pull requests merged in 2023-10, with the labels that each got.

#95 에러 바운더리 구현 및 적용
  client/package-lock.json
  client/package.json
  client/src/components/board/PostContent/index.tsx
  client/src/components/board/PostDetail/index.tsx
  client/src/components/common/ErrorFallback/index.tsx
  client/src/components/common/Skeleton/Box.tsx
  client/src/components/home/Loading/index.tsx
  client/src/components/home/PostsBox/index.tsx
  client/src/constants/constant.ts
  client/src/hooks/Main/useScroll.ts
  client/src/hooks/Write/useWriting.ts
  client/src/pages/404.tsx
  client/src/pages/board/[id].tsx
  client/src/pages/index.tsx
  client/src/service/base/api.ts
  client/src/service/board-post.ts
  client/src/service/comment-post.ts
  client/src/service/edit-profile.ts
  client/src/service/get-posts.ts
  client/src/service/login-post.ts
  client/src/service/sign-up.ts
  client/src/types/index.ts
Labels: DX, UX, Feature

#99 스토리북 적용 및 배포
  .github/workflows/chromatic.yml
  client/.eslintrc.json
  client/.gitignore
  client/.storybook/main.js
  client/.storybook/preview.js
  client/.storybook/public/main-duck.png
  client/.storybook/public/mockServiceWorker.js
  client/package-lock.json
  client/package.json
  client/public/advertise.png
  client/public/google_logo.png
  client/public/user_icon.png
  client/src/components/base/Layout/index.stories.tsx
  client/src/components/base/Layout/index.tsx
  client/src/components/common/Advertisement/index.stories.ts
  client/src/components/common/Advertisement/index.tsx
  client/src/components/common/Avatar/index.tsx
  client/src/components/common/ErrorFallback/index.stories.ts
  client/src/components/common/ErrorFallback/index.tsx
  client/src/components/common/MenuView/index.stories.tsx
  client/src/components/common/MenuView/index.tsx
  client/src/components/common/Navigator/index.stories.tsx
  client/src/components/common/Navigator/index.tsx
  client/src/components/common/Post/Comment/index.stories.tsx
  client/src/components/common/Post/Comment/index.tsx
  client/src/components/common/Post/CommentUpload/index.stories.tsx
  client/src/components/common/Post/CommentUpload/index.tsx
  client/src/components/common/Post/DeleteButton/index.tsx
  client/src/components/common/Post/ModifyCommentButton/index.tsx
  client/src/components/common/Post/ModifyContentButton/index.tsx
  client/src/components/common/Post/PostSummary/index.stories.tsx
  client/src/components/common/Post/PostSummary/index.tsx
  client/src/components/common/Post/index.tsx
  client/src/components/common/Post/post.tsx
  client/src/components/common/Skeleton/Box/index.stories.tsx
  client/src/components/common/Skeleton/Box/index.tsx
  client/src/components/common/Skeleton/Circle/index.stories.tsx
  client/src/components/common/Skeleton/Circle/index.tsx
  client/src/components/home/Loading/index.stories.tsx
  client/src/components/home/PostsBox/index.stories.tsx
  client/src/components/home/PostsBox/index.tsx
  client/src/components/home/WritePostButton/index.stories.tsx
  client/src/components/home/WritePostButton/index.tsx
  client/src/components/home/index.tsx
  client/src/components/index.tsx
  client/src/components/mygpt/SendButton/index.stories.tsx
  client/src/pages/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/signup/index.tsx
  client/src/types/index.ts
Labels: DX, Feature, Refactor

#102 채팅기능 구현
  client/package-lock.json
  client/package.json
  client/src/components/Chat/chat-message.tsx
  client/src/components/Chat/chat-room.tsx
  client/src/components/Chat/chat-user-list.tsx
  client/src/components/Chat/date-divider.tsx
  client/src/components/Chat/index.tsx
  client/src/components/Chat/user-tile.tsx
  client/src/components/common/MenuView/index.tsx
  client/src/components/common/Navigator/index.tsx
  client/src/components/common/UserInfo/index.tsx
  client/src/constants/constant.ts
  client/src/pages/chat/index.tsx
  client/src/pages/chatroom/index.tsx
  client/src/service/chat-get.ts
  client/src/service/chat-post.ts
  client/src/types/index.ts
  client/src/util/index.ts
Labels: UI, Feature
