Repository re-Duck/reDuck-client, pull requests merged in 2024-01, with the labels that each got.

#129 잘못된 useQuery를 useMutation으로 변경
  .github/workflows/lighthouse.yml
  client/next.config.js
  client/package.json
  client/src/components/board/PostContent/index.tsx
  client/src/components/board/PostDetail/index.tsx
  client/src/components/common/Post/Comment/index.stories.tsx
  client/src/components/common/Post/Comment/index.tsx
  client/src/components/common/Post/CommentUpload/index.tsx
  client/src/components/common/Post/DeleteButton/index.tsx
  client/src/pages/_app.tsx
  client/yarn.lock
Labels: DX, Refactor

#136 조회수 및 좋아요 수 기능 구현
  client/src/components/board/PostDetail/index.stories.tsx
  client/src/components/board/PostDetail/index.tsx
  client/src/components/common/Post/PostSummary/index.stories.tsx
  client/src/components/common/Post/PostSummary/index.tsx
  client/src/types/index.ts
  client/vercel.json
Labels: Feature

#144 merge: 게시글 링크 기능 추가
  README.md
  client/package.json
  client/src/components/board/PostDetail/index.tsx
  client/src/components/write/Toolbar/index.tsx
  client/src/components/write/icons/index.tsx
  client/src/components/write/icons/link.tsx
  client/src/hooks/Write/useTiptap.ts
  client/src/styles/tiptap.css
  client/yarn.lock
Labels: Feature

#147 팔로우 기능 구현
  client/package.json
  client/src/components/common/Alert/alert-icon.tsx
  client/src/components/common/Alert/index.tsx
  client/src/components/index.tsx
  client/src/components/profile/EditProfile/index.tsx
  client/src/components/profile/Follow/follow-button-errorfallback.tsx
  client/src/components/profile/Follow/follow-button.tsx
  client/src/components/profile/Follow/follow-list.tsx
  client/src/components/profile/Follow/follow-user-skeleton.tsx
  client/src/components/profile/Follow/follow-user.tsx
  client/src/components/profile/Follow/index.tsx
  client/src/components/profile/SideProfile/index.tsx
  client/src/components/profile/SideSkeleton/index.tsx
  client/src/components/profile/UserInfo/flex-label-content.tsx
  client/src/components/profile/UserInfo/index.tsx
  client/src/components/profile/index.tsx
  client/src/constants/constant.ts
  client/src/lib/redux/reducer/index.ts
  client/src/lib/redux/slices/alertSlice.ts
  client/src/pages/_app.tsx
  client/src/pages/profile/[id].tsx
  client/src/service/follow/cancleFollow.ts
  client/src/service/follow/checkFollowStatus.ts
  client/src/service/follow/getFollower.ts
  client/src/service/follow/getFollowing.ts
  client/src/service/follow/index.ts
  client/src/service/follow/requestFollow.ts
  client/src/service/user/index.ts
  client/src/service/user/logOutUser.ts
  client/src/types/index.ts
  client/src/types/redux/IAlert.ts
  client/src/types/redux/IReduxState.ts
  client/yarn.lock
Labels: UX, Feature
